font-family  = "Iosevka Nerd Font" 
theme = catppuccin-mocha
font-size = 15 
font-synthetic-style = false 
cursor-style = block
shell-integration-features = no-cursor
window-padding-y = 0, 0
window-padding-x = 0, 0 
