##### Prefix Key #####
set -g prefix C-Space

##### Shell and Terminal Setup #####
set-option -g default-shell /nix/store/vcrjkcll3rnr95xjql8rz57gjlhh2267-zsh-5.9/bin/zsh
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",alacritty:RGB"

set -g @plugin 'christoomey/vim-tmux-navigator'

# Copy-mode bindings (no harm)
bind -T copy-mode-vi C-h select-pane -L
bind -T copy-mode-vi C-j select-pane -D
bind -T copy-mode-vi C-k select-pane -U
bind -T copy-mode-vi C-l select-pane -R
bind -T copy-mode-vi C-\\ select-pane -l
bind -T copy-mode-vi C-Space select-pane -t:.+

##### Floax Plugin Config #####
set -g @plugin 'omerxx/tmux-floax'
set -g @floax-bind '-n M-p'
set -g @floax-title 'sky'
set -g @floax-text-color 'white'

##### Sessionx Plugin Config #####
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'K'

##### TPM (Plugin Manager) #####
set -g @plugin 'tmux-plugins/tpm'

##### Statusbar #####
set-option -g status-left-length 100
set -g status-justify absolute-centre
set -g status-left '#S'
set -g status-left-style 'fg=#f38ba8'
set -g status-right ''
set -g status-style 'bg=#11111b'
set-option -g status-position top
setw -g window-status-current-style 'bg=default bold'
setw -g window-status-current-format '#I:#W '

##### Window Management #####
unbind '"'
bind '"' split-window -h -c "#{pane_current_path}"
unbind %
bind % split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

##### Appearance #####
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
set -g renumber-windows on
set -g base-index 1
setw -g mode-keys vi
set -g mouse off
##### Reload Config #####
unbind r
bind r source-file ~/.config/tmux/tmux.conf

##### Custom Scripts #####
bind-key C-k display-popup -E -w 40% "sesh connect \"$(sesh list --hide-duplicates -i | gum filter --limit 1 --placeholder 'Pick a Sesh' --prompt='⚡')\""

run  '~/.tmux/plugins/tpm/tpm'
